# Generated by Django 2.1.2 on 2018-10-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181006_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultynotifications',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultynotifications',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
