# Generated by Django 2.1.2 on 2018-10-05 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181006_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultynotifications',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_receiver', to='app.Faculty'),
        ),
        migrations.AlterField(
            model_name='facultynotifications',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_sender', to='app.Faculty'),
        ),
    ]
