# Generated by Django 2.1.2 on 2018-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
