# Generated by Django 2.1.2 on 2018-10-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project_reject_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reject_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('is_need_changes', models.BooleanField(default=False)),
                ('changes_required', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='reject_reason',
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
