# Generated by Django 2.1.2 on 2018-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181006_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
